### ISSUE TITLE
on install the first time i start up stardew valley it is fine but when starting up a second time it crashes on startup and gives this error message i have tried to reinstal the mod and i keep having this issue 

### ISSUE THREAD

**Issue by riddler176** [daleao/modular-overhaul#105]
[Modular Gameplay Overhaul] Mod crashed on entry and might not work correctly. Technical details:
Newtonsoft.Json.JsonReaderException: Can't parse JSON file at c:\program files (x86)\steam\steamapps\common\Stardew Valley\Mods\ModularOverhaul\config.json.
Technical details: Error setting value to 'EnableAutoSelection' on 'DaLion.Overhaul.Modules.Combat.CombatConfig'.
   at StardewModdingAPI.Toolkit.Serialization.JsonHelper.ReadJsonFileIfExists[TModel](String fullPath, TModel& result) in SMAPI.Toolkit\Serialization\JsonHelper.cs:line 86
   at StardewModdingAPI.Framework.ModHelpers.DataHelper.ReadJsonFile[TModel](String path) in SMAPI\Framework\ModHelpers\DataHelper.cs:line 50
   at StardewModdingAPI.Framework.ModHelpers.ModHelper.ReadConfig[TConfig]() in SMAPI\Framework\ModHelpers\ModHelper.cs:line 152
   at DaLion.Overhaul.ModEntry.Entry(IModHelper helper) in C:\dev\sdv\mods\1.5\Modular Overhaul\ModEntry.cs:line 99
   at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in SMAPI\Framework\SCore.cs:line 1810

**Comment by daleao** [comment]
Delete just this line from your config: `EnableAutoSelection`.
