### ISSUE TITLE
Game softlocking on end-of-day save with Combat Module after recent update.

### ISSUE THREAD

**Issue by calephelis** [daleao/modular-overhaul#110]
Unable to save and progress to the next day unless the Combat Module is disabled. Full SMAPI log is [here](https://smapi.io/log/dfb22fed6d1b46bf8a1e5a3074348c9a), but here's the relevant text:

15:12:53 | ERROR | game | InvalidOperationException: There was an error generating the XML document.  
---> InvalidOperationException: There was an error generating the XML document.  
---> InvalidOperationException: The type DaLion.Overhaul.Modules.Combat.Enchantments.DaggerEnchantment was not expected. Use the XmlInclude or SoapInclude attribute to specify types that are not known statically.    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write84_BaseEnchantment(String n, String ns, BaseEnchantment o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write19_MeleeWeapon(String n, String ns, MeleeWeapon o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write49_Item(String n, String ns, Item o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write20_Chest(String n, String ns, Chest o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write48_Object(String n, String ns, Object o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write100_Object(Object o)    
--- End of inner exception stack trace ---    
at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)    
at StardewValley.SerializableDictionary`2.WriteXml(XmlWriter writer) in stardewvalley\Farmer\Farmer\SerializableDictionary.cs:line 138    
at System.Xml.Serialization.XmlSerializationWriter.WriteSerializable(IXmlSerializable serializable, String name, String ns, Boolean isNullable, Boolean wrapped)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write112_Farm(String n, String ns, Farm o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write188_GameLocation(String n, String ns, GameLocation o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write237_SaveGame(String n, String ns, SaveGame o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write238_SaveGame(Object o)    
--- End of inner exception stack trace ---    
at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)    
at SpaceCore.Patches.SaveGamePatcher.SerializeProxy(XmlSerializer serializer, XmlWriter origWriter, Object obj) in C:\Programming\StardewValley\ModSource\SpaceCore\Patches\SaveGamePatcher.cs:line 401    
at StardewValley.SaveGame+<getSaveEnumerator>d__90.MoveNext_PatchedBy<spacechase0.SpaceCore>(<getSaveEnumerator>d__90 this)    
at StardewValley.SaveGame.<>c__DisplayClass88_0.<Save>b__0()    
at System.Threading.Tasks.Task.InnerInvoke()    
at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)    
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) 
--- End of stack trace from previous location ---    
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)    
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

15:12:53 | ERROR | SMAPI | An error occurred in the overridden update loop: InvalidOperationException: There was an error generating the XML document.  
---> InvalidOperationException: There was an error generating the XML document.  
---> InvalidOperationException: The type DaLion.Overhaul.Modules.Combat.Enchantments.DaggerEnchantment was not expected. Use the XmlInclude or SoapInclude attribute to specify types that are not known statically.    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write84_BaseEnchantment(String n, String ns, BaseEnchantment o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write19_MeleeWeapon(String n, String ns, MeleeWeapon o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write49_Item(String n, String ns, Item o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write20_Chest(String n, String ns, Chest o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write48_Object(String n, String ns, Object o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write100_Object(Object o)    
--- End of inner exception stack trace ---    
at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)    
at StardewValley.SerializableDictionary`2.WriteXml(XmlWriter writer) in stardewvalley\Farmer\Farmer\SerializableDictionary.cs:line 138    
at System.Xml.Serialization.XmlSerializationWriter.WriteSerializable(IXmlSerializable serializable, String name, String ns, Boolean isNullable, Boolean wrapped)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write112_Farm(String n, String ns, Farm o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write188_GameLocation(String n, String ns, GameLocation o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write237_SaveGame(String n, String ns, SaveGame o, Boolean isNullable, Boolean needType)    
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write238_SaveGame(Object o)    
--- End of inner exception stack trace ---    
at StardewValley.SaveGame.Save()+MoveNext() in stardewvalley\Farmer\Farmer\SaveGame.cs:line 416    
at StardewValley.Menus.SaveGameMenu.update_PatchedBy<spacechase0.SpaceCore>(SaveGameMenu this, GameTime time)    
at StardewValley.Menus.ShippingMenu.update(GameTime time)    
at StardewValley.Game1._update(GameTime gameTime)    
at StardewValley.Game1.Update(GameTime gameTime)    
at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate)

**Comment by daleao** [comment]
Whatever dagger you have on you, try running the 'cmbt refresh' command while holding it. If that does not work, try to trash it and spawn a new one.

Fyi Trash Does Not Consume Bait and Watering XP, Crops Wither mods are both included in TWX module.

**Comment by calephelis** [comment]
(Whoops, forgot I still had those mods installed.)

Anyway, 'cmbt refresh' seems to have fixed it, thank you!
