### ISSUE TITLE
Luremaster's Magic bait effect no longer works

### ISSUE THREAD

**Issue by Jumping-notes** [daleao/modular-overhaul#117]
https://smapi.io/log/5f1ca738b6164bb58da9c6dc6bd07f93

23:37:00	ERROR	Modular Gameplay Overhaul	Failed in CrabPotDayUpdatePrefix:
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at DaLion.Overhaul.Modules.Professions.Extensions.CrabPotExtensions.ChooseFish(CrabPot crabPot, Dictionary`2 fishData, GameLocation location, Random r) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\Professions\Extensions\CrabPotExtensions.cs:line 161
   at DaLion.Overhaul.Modules.Professions.Patchers.Fishing.CrabPotDayUpdatePatcher.CrabPotDayUpdatePrefix(CrabPot __instance, GameLocation location) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\Professions\Patchers\Fishing\CrabPotDayUpdatePatcher.cs:line 59
23:37:00	ERROR	Modular Gameplay Overhaul	Failed in CrabPotDayUpdatePrefix:
System.Collections.Generic.KeyNotFoundException: The given key '-1' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DaLion.Overhaul.Modules.Professions.Extensions.CrabPotExtensions.ChooseFish(CrabPot crabPot, Dictionary`2 fishData, GameLocation location, Random r) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\Professions\Extensions\CrabPotExtensions.cs:line 112
   at DaLion.Overhaul.Modules.Professions.Patchers.Fishing.CrabPotDayUpdatePatcher.CrabPotDayUpdatePrefix(CrabPot __instance, GameLocation location) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\Professions\Patchers\Fishing\CrabPotDayUpdatePatcher.cs:line 59

**Comment by daleao** [comment]
Thanks. Fixed for next update.
