### ISSUE TITLE
Unable to see skills menu

### ISSUE THREAD

**Issue by Belsasim** [daleao/modular-overhaul#167]
I'm not sure this is caused by Modular Overhaul, but SMAPI is mentioning the mod. When I try to access the Skills tab in the in game menu, the menu just closes.

SMAPI gives me this:

[SMAPI] The StardewValley.Menus.GameMenu menu crashed while drawing itself. SMAPI will force it to exit to avoid crashing the game.
ArgumentException: The IMargoAPI interface defines method GetConfig which doesn't exist in the API or depends on an interface that cannot be mapped!
   at Nanoray.Pintail.ProxyManagerConfiguration`1.<>c.<.cctor>b__15_4(TypeBuilder proxyBuilder, ProxyInfo`1 proxyInfo, FieldBuilder _, FieldBuilder _, FieldBuilder _, MethodInfo proxyMethod)
   at Nanoray.Pintail.InterfaceOrDelegateProxyFactory`1.Prepare(ProxyManager`1 manager, String typeName)
   at Nanoray.Pintail.ProxyManager`1.ObtainProxyFactory(ProxyInfo`1 proxyInfo)
   at Nanoray.Pintail.IProxyManagerExtensions.ObtainProxy[Context,TProxy](IProxyManager`1 self, Object instance, Context targetContext, Context proxyContext)
   at StardewModdingAPI.Framework.ModHelpers.ModRegistryHelper.GetApi[TInterface](String uniqueID) in SMAPI\Framework\ModHelpers\ModRegistryHelper.cs:line 133
   at Shockah.XPDisplay.MargoBridge.SetupIfNeeded() in C:\git\Stardew-Valley-Mods\XPDisplay\MargoBridge.cs:line 17
   at Shockah.XPDisplay.MargoBridge.IsPrestigeEnabled() in C:\git\Stardew-Valley-Mods\XPDisplay\MargoBridge.cs:line 22
   at Shockah.XPDisplay.XPDisplay.SkillsPage_draw_QueueDelegate(SpriteBatch b, Int32 x, Int32 y, Int32 levelIndex, Int32 uiSkillIndex, String spaceCoreSkillName) in C:\git\Stardew-Valley-Mods\XPDisplay\XPDisplay.cs:line 784
   at SpaceCore.Interface.NewSkillsPage.draw_PatchedBy<DaLion.Overhaul.Modules.Professions__Shockah.XPDisplay>(NewSkillsPage this, SpriteBatch b)
   at StardewValley.Menus.GameMenu.draw(SpriteBatch b)
   at StardewModdingAPI.Framework.SGame.DrawImpl(GameTime gameTime, RenderTarget2D target_screen) in SMAPI\Framework\SGame.cs:line 920

I'm playing on a Mac and do have quite a lot of other mods running.

**Comment by daleao** [comment]
Need you to share a log please.
Refer to the README.

**Comment by gustavosouza1997** [comment]
Had the same issue a while back, its because the mod XP Displays is incompatible with Margo.

**Comment by Belsasim** [comment]
Hello, thanks for the quick reactions! I did have the XP Display mod, so I removed it and everything works fine now. 
Thank you for your help and thanks for this great mod, I love all the modules!

**Comment by daleao** [comment]
It's stated at the top of each release that they are no longer compatible.
Just scroll down the Releases until you find one that doesn't have the warning.
Should work on any version older than 4.2.
