### ISSUE TITLE
Error when loading smappi

### ISSUE THREAD

**Issue by Kyswitchblade** [daleao/modular-overhaul#170]
Error on smappi crash on load
[Modular Gameplay Overhaul] [Harmonizer]: Failed to apply Game1CheckForEscapeKeysPatcher.
Harmony returned System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Couldn't find method checkForEscapeKeysPatcher NULL in type StardewValley.Game1.
   at CommunityToolkit.Diagnostics.ThrowHelper.ThrowMissingMethodException[T](String message)
   at DaLion.Overhaul.Modules.Combat.Patchers.Melee.Game1CheckForEscapeKeysPatcher..ctor() in G:\modded\sdv\dev\main\margo\Modules\Combat\Patchers\Melee\Game1CheckForEscapeKeysPatcher.cs:line 19
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at DaLion.Shared.Harmony.Harmonizer.ApplyImplicitly(Func`2 predicate) in G:\modded\sdv\dev\main\Shared\Harmony\Harmonizer.cs:line 165

**Comment by Kyswitchblade** [comment]
For more details I make it to main menu, but it crashes when I try to load a farm.

**Comment by chengzi-cmd** [comment]
我也出现了这种问题
出现问题的主要原因：
本模组启用战斗模块会产生错误，不启用战斗模块则不会产生错误

**Comment by daleao** [comment]
This can be safely ignored. I will push out a fix for this soon but it literally doesn't do anything.

**Comment by Kyswitchblade** [comment]
A different mod was causing the crash.
Thanks for letting me know.
