### ISSUE TITLE
Error in the Smapi console

### ISSUE THREAD

**Issue by BriseisDraghost** [daleao/modular-overhaul#176]
Hello,

I am using the Modular Overhaul in one of my slot and this error shows up:

[Modular Gameplay Overhaul] [Harmonizer]: Failed to apply Game1CheckForEscapeKeysPatcher.
Harmony returned System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Couldn't find method checkForEscapeKeysPatcher NULL in type StardewValley.Game1.
   at CommunityToolkit.Diagnostics.ThrowHelper.ThrowMissingMethodException[T](String message)
   at DaLion.Overhaul.Modules.Combat.Patchers.Melee.Game1CheckForEscapeKeysPatcher..ctor() in G:\modded\sdv\dev\main\margo\Modules\Combat\Patchers\Melee\Game1CheckForEscapeKeysPatcher.cs:line 19
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at DaLion.Shared.Harmony.Harmonizer.ApplyImplicitly(Func`2 predicate) in G:\modded\sdv\dev\main\Shared\Harmony\Harmonizer.cs:line 165

I have also have to say that every second of the month yes, taxes are applied but according to the mail the total deduced is 0 even if it's not true.

What can I do?

Thank you!

**Comment by timroham** [comment]
I also have this error pop up immediately on game load after updating to the latest version.

**Comment by HanMeimei3310** [comment]
ME！！TOO！！！

**Comment by tjdwo13579** [comment]
Same here

**Comment by tjdwo13579** [comment]
I have found a workaround for anyone interested.
Delete the mod folder and download a fresh folder of the mod.

**Comment by daleao** [comment]
Issue can be ignored.
