### ISSUE TITLE
Latest version of MARGO causes smapi error

### ISSUE THREAD

**Issue by DuneReference** [daleao/modular-overhaul#185]
I'm not sure if this error has an effect I should be worried about, but with only the latest versions of SpaceCore and MARGO (1.17.2/4.2.3) installed it throws an error on startup not being able to find method checkForEscapeKeysPatcher.

I have an old version of SpaceCore/MARGO (1.13.0/2.3.1) and I don't get this error

latest version gives this output in the SMAPI console:
```
[SMAPI] Launching mods...
[Modular Gameplay Overhaul] [Modules]: Core module activated.
[Modular Gameplay Overhaul] [Modules]: Shared features activated.
[Modular Gameplay Overhaul] [Modules]: Professions module activated.
[Modular Gameplay Overhaul] [Harmonizer]: Failed to apply Game1CheckForEscapeKeysPatcher.
Harmony returned System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Couldn't find method checkForEscapeKeysPatcher NULL in type StardewValley.Game1.
   at CommunityToolkit.Diagnostics.ThrowHelper.ThrowMissingMethodException[T](String message)
   at DaLion.Overhaul.Modules.Combat.Patchers.Melee.Game1CheckForEscapeKeysPatcher..ctor() in G:\modded\sdv\dev\main\margo\Modules\Combat\Patchers\Melee\Game1CheckForEscapeKeysPatcher.cs:line 19
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at DaLion.Shared.Harmony.Harmonizer.ApplyImplicitly(Func`2 predicate) in G:\modded\sdv\dev\main\Shared\Harmony\Harmonizer.cs:line 165
[Modular Gameplay Overhaul] [Modules]: Combat module activated.
[Modular Gameplay Overhaul] [Modules]: Tools module activated.
[Modular Gameplay Overhaul] [Modules]: Ponds module activated.
[Modular Gameplay Overhaul] [Modules]: Taxes module activated.
[Modular Gameplay Overhaul] [Modules]: Tweex module activated.
[Modular Gameplay Overhaul] [Entry]: Version checksum: 5825dc86029b3c746b86baf7e42979aa
[SMAPI] Mods loaded and ready!
```

**Comment by DuneReference** [comment]
Looks like it's from the latest version 4.2.3 and the transpiled function is blank so it's probably just a template for functionality to be added in the future or something. Seems like I should just be able to ignore it.

**Comment by JustJulzz** [comment]
I am getting the same Error but it works just fine in game.
