### ISSUE TITLE
Failed in MeleeWeaponGetItemLevelPrefix

### ISSUE THREAD

**Issue by oDolohov** [daleao/modular-overhaul#90]
https://smapi.io/log/3a5c30688a864e688bfeb37ed9016048

12:24:08 | ERROR | Modular Gameplay Overhaul | Failed in MeleeWeaponGetItemLevelPrefix: System.FormatException: Input string was not in a correct format.    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)    at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)    at DaLion.Overhaul.Modules.Combat.VirtualProperties.MeleeWeapon_Stats.Create(MeleeWeapon weapon) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\Combat\VirtualProperties\MeleeWeapon_Stats.cs:line 304    at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)    at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)    at DaLion.Overhaul.Modules.Combat.VirtualProperties.MeleeWeapon_Stats.Get_Level(MeleeWeapon weapon) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\Combat\VirtualProperties\MeleeWeapon_Stats.cs:line 203    at DaLion.Overhaul.Modules.Combat.Patchers.Melee.MeleeWeaponGetItemLevelPatcher.MeleeWeaponGetItemLevelPrefix(MeleeWeapon __instance, Int32& __result) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\Combat\Patchers\Melee\MeleeWeaponGetItemLevelPatcher.cs:line 44

**Comment by daleao** [comment]
Can you give some context? What weapon is this?

**Comment by Erin105** [comment]
Seem to be getting the exact same error when opening the Lookup Anything mod search window.

[Modular Gameplay Overhaul] Failed in MeleeWeaponGetItemLevelPrefix:
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at DaLion.Overhaul.Modules.Combat.VirtualProperties.MeleeWeapon_Stats.Create(MeleeWeapon weapon) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\Combat\VirtualProperties\MeleeWeapon_Stats.cs:line 304
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at DaLion.Overhaul.Modules.Combat.VirtualProperties.MeleeWeapon_Stats.Get_Level(MeleeWeapon weapon) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\Combat\VirtualProperties\MeleeWeapon_Stats.cs:line 203
   at DaLion.Overhaul.Modules.Combat.Patchers.Melee.MeleeWeaponGetItemLevelPatcher.MeleeWeaponGetItemLevelPrefix(MeleeWeapon __instance, Int32& __result) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\Combat\Patchers\Melee\MeleeWeaponGetItemLevelPatcher.cs:line 44

**Comment by daleao** [comment]
Are you searching for anything specific?
Just opening the search window doesn't cause any issues for me.

**Comment by Erin105** [comment]
No searching, just opening the search window.

After testing it's Ridgeside village, specifically the Fairy Needle.

**Comment by daleao** [comment]
Thanks, that helps immensely.
