### ISSUE TITLE
Mod Crash at the start and didnt load into game

### ISSUE THREAD

**Issue by MMSH1996** [daleao/modular-overhaul#92]
it happened after the updates of 4.1.0 and 4.1.1 where i had to delete the old file 4.0.1 which was working fine without errors then after I downloaded 4.1.0 I tried to replace the new config with the old one so i dont have to change the settings all over again but it gave me some error and didnt work so I deleted and copied it again without the old config file and it worked, then the next day 4.1.1 came out and it gave another red text at first but then worked fine and now it gave the red text again even though no changes have been made or new mods downloaded 

the error text in SMAPI 

[Modular Gameplay Overhaul] Mod crashed on entry and might not work correctly. Technical details:
Newtonsoft.Json.JsonReaderException: Can't parse JSON file at F:\Steam\steamapps\common\Stardew Valley\Mods\ModularOverhaul\config.json.
Technical details: Error setting value to 'EnableAutoSelection' on 'DaLion.Overhaul.Modules.Combat.CombatConfig'.
   at StardewModdingAPI.Toolkit.Serialization.JsonHelper.ReadJsonFileIfExists[TModel](String fullPath, TModel& result) in SMAPI.Toolkit\Serialization\JsonHelper.cs:line 86
   at StardewModdingAPI.Framework.ModHelpers.DataHelper.ReadJsonFile[TModel](String path) in SMAPI\Framework\ModHelpers\DataHelper.cs:line 50
   at StardewModdingAPI.Framework.ModHelpers.ModHelper.ReadConfig[TConfig]() in SMAPI\Framework\ModHelpers\ModHelper.cs:line 152
   at DaLion.Overhaul.ModEntry.Entry(IModHelper helper) in C:\dev\sdv\mods\1.5\Modular Overhaul\ModEntry.cs:line 99
   at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in SMAPI\Framework\SCore.cs:line 1810

**Comment by daleao** [comment]
The error clearly says  "Error setting value to 'EnableAutoSelection'".
Either delete your whole config, or delete just that one field.
